project_id = "villgquhqycufwkynwjl"

[functions.voice-assistant]
verify_jwt = false

[functions.satellite-analysis]
verify_jwt = true

[functions.soil-analysis]
verify_jwt = true

[functions.weather-alerts]
verify_jwt = false

[functions.market-prices]
verify_jwt = false

[functions.sms-service]
verify_jwt = true