// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://villgquhqycufwkynwjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpbGxncXVocXljdWZ3a3lud2psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDQwNjksImV4cCI6MjA2OTEyMDA2OX0.oFoS-e0SxY5aF4yf7OqZuHdz5BXju1PTcB9XaRWu5Uw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});